before:
  hooks:
    - go mod tidy
    - go fmt ./...
builds:
  - main: '.'
    binary: sac
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - -s -w -X github.com/stuxcd/admission-controller/cmd.version={{.Version}}
      - -X github.com/stuxcd/admission-controller/cmd.commit={{.Commit}}
      - -X github.com/stuxcd/admission-controller/cmd.date={{.Date}}
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
