{{ $ca := genCA "admission-controller-ca" 365 }}
{{ $cn := printf "admission-controller.%s.svc.cluster.local" .Release.Namespace }}
{{ $server := genSignedCert $cn nil nil 365 $ca }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "admission-controller.fullname" . }} 
type: Opaque
data:
  {{- if .Values.server.certData }}
  cert.pem: {{ .Values.server.certData }}
  {{- else }}
  cert.pem: {{ b64enc $server.Cert }}
  {{ end }}
  {{- if .Values.server.keyData }}
  key.pem: {{ .Values.server.keyData }}
  {{- else }}
  key.pem: {{ b64enc $server.Key }}
  {{ end }}